name: flutter_widgets
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0
  flutter: ^3.24.0

dependencies:
  flutter:
    sdk: flutter
  app_services:
    path: ../app_services  
  imovie_ui:
    path: ../imovie_ui
  models:
    path: ../models
    
  http: ^1.1.2  
  speech_to_text: ^6.6.0
  avatar_glow: ^3.0.1
  shimmer: ^3.0.0
  youtube_player_flutter: ^9.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
